name: siesa_customer_support_web_3
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  go_router: ^4.3.0
  
  flutter_riverpod: ^1.0.4

  dio: ^4.0.6

  animate_do: ^2.1.0

  logger: ^1.1.0

  card_swiper: ^2.0.4

  font_awesome_flutter: ^10.1.0

  url_launcher: ^6.1.5

  flutter_svg: ^1.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/i18n/
    - assets/svg/
    - assets/images/
    - assets/images/stocks/
